apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager # Name and namespace here are before any OpenShift modifications
  namespace: system
spec:
  template:
    spec:
      containers:
        - name: manager
          env:
            - name: EXP_ASO_API
              value: "false"
